# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d4e275dbccc669053486d5dac1b03d3"
name = "mtindo-store"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
