"""add shopify inventory item id

Revision ID: 901f4f51b485
Revises: d06e32ec037c
Create Date: 2026-04-10 18:51:33.620585
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '901f4f51b485'
down_revision: Union[str, Sequence[str], None] = 'd06e32ec037c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shopify_inventory_item_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'shopify_inventory_item_id')
    # ### end Alembic commands ###
