"""add_shopify_ids_to_product

Revision ID: d06e32ec037c
Revises: 20260408_02
Create Date: 2026-04-09 12:15:38.079831
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd06e32ec037c'
down_revision: Union[str, Sequence[str], None] = '20260408_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.add_column('products', sa.Column('shopify_id', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('shopify_variant_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_products_shopify_id'), 'products', ['shopify_id'], unique=True)
    op.create_unique_constraint(None, 'products', ['shopify_variant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_shopify_id'), table_name='products')
    op.drop_column('products', 'shopify_variant_id')
    op.drop_column('products', 'shopify_id')
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###
